### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by xhendrikg** [pranavgade20/FabricHax#10]
Do you have a Discord? Can you enable GitHub wiki?

**Comment by pranavgade20** [comment]
My discord is 'import username#8314'

I haven't considered GitHub wiki, but that's a great idea! Would you consider helping a bit?

**Comment by xhendrikg** [comment]
> 
> 
> My discord is 'import username#8314'
> 
> I haven't considered GitHub wiki, but that's a great idea! Would you consider helping a bit?

yes what can i do?

**Comment by pranavgade20** [comment]
You can contribute to writing any wiki page you like, because all it has right now is a basic readme page.
