### ISSUE TITLE
Automine

### ISSUE THREAD

**Issue by Ashiix** [pranavgade20/FabricHax#11]
An automine config would be wonderful, allowing users to select specific blocks, etc. Not sure if it's intended, but automine breaks much slower than Nuker on other mods such as ForgeHax.

**Comment by pranavgade20** [comment]
Yup, I think it's a good idea. Unfortunately, I'm a bit busy right now implementing the scripting part, so I don't think that's a high priority :)

And this mostly a mod for survival mode, so the speed of automine is whatever your current tool allows. I have a few more features planned for survival, so I'm going to implement them before customising the mod for creative mode.

**Comment by Ashiix** [comment]
Sounds good, good luck :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pranavgade20** [comment]
https://github.com/pranavgade20/FabricHax/commit/81ff3f1b0861a4db79673e5fabf58c20e59d1b6f implements this. You can get the jar here(https://github.com/pranavgade20/FabricHax/releases/tag/v1.3.6)
