### ISSUE TITLE
issue with freecam

### ISSUE THREAD

**Issue by truliny** [pranavgade20/FabricHax#12]
on servers if i use freecam and turn it off, the game crashes and if i try to use it, it doesnt work instead i fall in a endless void

mods >

sodium
lithium
starlight
perspectiveredux
modmenu

please fix this

**Comment by pranavgade20** [comment]
Hi! Thanks for your report!

I do know that that is an issue, and I have attempted an fix. Here's a nightly build, before I release it:

[fabrichax-1.3.1.zip](https://github.com/pranavgade20/FabricHax/files/6618945/fabrichax-1.3.1.zip)

If your game still crashes while using this, I'd appreciate it if you could provide error logs as well(you usually get a view details option when launcher starts after crash)

**Comment by truliny** [comment]
thank you its working now

**Comment by truliny** [comment]
it works now
