### ISSUE TITLE
Baritone Implementation?

### ISSUE THREAD

**Issue by greymesa** [pranavgade20/FabricHax#16]
Are there any plans to bundle baritone in fabrichax? also asking cause baritone still doesn't have a 1.17 release, let alone a fabric one like 1.16.5 did.

**Comment by Gaming32** [comment]
This issue is outdated as Baritone now supports 1.17 and 1.18, and has for a while, it turns out.

**Comment by greymesa** [comment]
> This issue is outdated as Baritone now supports 1.17 and 1.18, and has for a while, it turns out.

Closing.
