### ISSUE TITLE
Add animal feeding

### ISSUE THREAD

**Issue by esbe1175** [pranavgade20/FabricHax#17]
Can you add a feature that automatically feeds animals nearby with what you are holding?
This is especially useful for situations where you have auto-farms with a LOT of animals in a small area. Clicking all of them is practically impossible, since they're blocked by other animals 95% of the time.

Would be amazing!

**Comment by pranavgade20** [comment]
Thanks for the great idea! This feature is added in 2fcdecb33dbae92c5719741c11f32c7b79119687. You can head over to https://github.com/pranavgade20/FabricHax/releases/tag/v.1.3.8 and get the jar for this.

**Comment by esbe1175** [comment]
Wow thanks a lot! You got around to that so fast.
