### ISSUE TITLE
i cant make it work

### ISSUE THREAD

**Issue by nivkabiri** [pranavgade20/FabricHax#22]
I'm really trying to lunch my game but it's crashing all the time this is whats up its says "exit code 1"

**Comment by csandrew-dev** [comment]
You need to follow this guide from fabric if you are trying to use the client through the mc launcher. Go to https://fabricmc.net/ then download fabric loader and api. Follow this https://fabricmc.net/wiki/install.

**Comment by pranavgade20** [comment]
Hey! The latest release might fix this - if not, please add the crash report. Crash reports can be found in .minecraft -> crash-reports
