### ISSUE TITLE
i think it doesm't work in fabric minecraft 1.19.2

### ISSUE THREAD

**Issue by nivkabiri** [pranavgade20/FabricHax#23]
please update the files or help me fix it

**Comment by csandrew-dev** [comment]
You have to update the gradle.properties file to current fabric release on https://fabricmc.net/develop/ then change the fabric.mod.json file to say "1.19.x" but I think the repo already does so you're good there. Then you should be all good.

**Comment by pranavgade20** [comment]
https://github.com/pranavgade20/FabricHax/releases/tag/v1.19.3.0 updates the mod to 1.19.3
